networks:
  public:
    external:
      name: frontend
  private:
services:
  weather:
    build:
      context: ./
      dockerfile: "php.Dockerfile"
    restart: "always"
    ports:
      - "1000:1000"
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html
      - type: bind
        source: ./log
        target: /var/log/apache2
    networks:
      - public
      - private
    environment:
      - MARIADB_USER=${MARIADB_USER:-utest}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-utest}
      - MARIADB_DATABASE=weather
      - MARIADB_DATABASE_TABLE_NAME=canberra_data
      - WEATHER_STATION_ADDRESS=http://192.168.1.200:1000
      - TZ=Australia/Canberra
  db:
    build:
      context: ./
      dockerfile: mariadb.Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=${MARIADB_USER:-utest}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-utest}
      - MARIADB_DATABASE=weather
      - TZ=Australia/Canberra
    volumes:
      - type: bind
        source: ./sql/db
        target: /var/lib/mysql
      - type: bind
        source: ./sql/init
        target: /docker-entrypoint-initdb.d
    networks:
      - private
